FROM node:16-alpine as build
# set working directory
WORKDIR /app
# install app dependencies
COPY package*.json ./
RUN npm install
# add app
COPY . ./
RUN npm run build

FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
